package com.company.enums;

public enum AdminStatus {
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    SELECT_EDIT_PRODUCT_NAME,
    SELECT_EDIT_PRODUCT_PRICE,
    SELECT_EDIT_PRODUCT_IMAGE, SELECT_ADD_PRODUCT

}
